netlify/netlifyctl

commands/netlify.go, commands/sites.go, main.go
I think reference to the import needs to be changed from calavera to netlify.
I get the following error when running `go get`:
```bash
Cloning into '/Users/bdougie/go/src/github.com/calavera/netlify-go-cli'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/calavera/netlify-go-cli/auth: exit status 128
```
=> switch the github user to netlify

commands/deploy/deploy.go, commands/netlify.go, configuration/configuration.go
- Added “-C” flag to allow setting the netlify config file to be used when deploying.
- Fixed minor warnings due to variable assignment overrides.
=> Added "-C" flag to allow setting the netlify config file to be used

commands/commands.go, commands/middleware/middleware.go, commands/netlify.go
Use a middleware to unset the debug mode after the command runs.
=> Enable open-api debug mode when -D is set.

commands/commands.go, commands/middleware/middleware.go, commands/sites/sites.go, commands/sites/update.go, configuration/configuration.go, configuration/site.go, operations/site.go
Allowing to modify these fields:
- Site name
- Site custom domain
- Site TLS setting
- Site password
- Domain aliases
Open editor when no flags are set.
=> Implement site update.

operations/ui.go
It turns out that Go will put a nil into the array in this case. I thought it would just give you a nil array or an empty array, but apparently not.
https://play.golang.org/p/3DoalqMkiQ
=> update to test for nil in validators

operations/site.go
We compensate for the [0] to make a new site. We have to recompensate when selecting.
=> fix indexing issue

glide.lock
This fixes the runtime setting the Transfer-Encoding: chunked header in cases where it did not need to.
Fixes #39
=> Update go-openapi runtime

commands/assets/add.go, commands/assets/assets.go, commands/assets/info.go, commands/assets/list.go, commands/commands.go, commands/deploy/deploy.go, commands/middleware/middleware.go, commands/netlify.go, configuration/configuration.go, glide.lock, glide.yaml
- `asset add` to upload an asset for a site.
- `asset list` to list all the assets for a site.
- `asset info` to show the information for a specific asset.
It requires this version of open-api https://github.com/netlify/open-api/pull/27
=> Add Site assets commands.

commands/deploy/deploy.go, commands/sites/create.go, commands/sites/sites.go, commands/sites/update.go, glide.lock, glide.yaml, operations/site.go
This is useful when explcitly creating a site with a session id
before deploying.
=> Add support for creating a blank site

commands/commands.go, commands/middleware/middleware.go, commands/netlify.go, glide.lock, glide.yaml
This allows people to have a debug log right away that can share with
Netlify for troubleshooting.
- Keep the log in memory.
- Dump it to a file if there is an error before terminating the command.
=> Turn debug log always on.

commands/assets/list.go, commands/sites/sites.go, glide.lock, glide.yaml
For some weird reason, the library we were using doesn't print
if the information to print overflows the screen height.
That behaviour is very unexpected and wrong.
This removes that library and uses tabwriter directly, removing one
dependency and doing the right thing.
=> Fix site listing with sites overflowing the screen size.

ui/task_tracker.go
Check if we have a terminal before printing the message.
Fixes #64, #65
=> Fix step tracker.

commands/commands.go, commands/middleware/middleware.go, commands/sites/update.go
This ensure that the api client is configured before any call to the api.
Fixes #77
=> Reverse middlewares ordering.

commands/sites/sites.go
Currently `netlifyctl site` output looks like (e.g.):
```sh
me@host:~$ netlifyctl site
Site              Url
site001          https://www.example.com
mynewsite002     https://www.example.comme@host:~$ 
```
this PR reformats it to look like this:
```sh
me@host:~$ netlifyctl site
Site              Url
site001          https://www.example.com
mynewsite002     https://www.example.com
me@host:~$ 
```
=> when listing sites to the console, end on new line

commands/init/init.go, ui/task_tracker.go, ui/ui.go
Otherwise, the term hangs forever without allowing users to add inputs.
Fixes #91
=> Ignore term animations in manual init command.

README.md
Without doing this, redirects and headers defined in the toml file will not work.
=> Include caveat about putting netlify.toml in the publish directory

commands/commands.go, commands/forms/forms.go, commands/forms/submissions.go, glide.lock, glide.yaml
It was suggested in Issue #6 and I have added a new command and one subcommand to netlifyctl: `$ netlifyctl form`.
Running the forms command will list out every form a user has access to with the following fields: form name, form id, site id, and number of submissions.
As well, you can view basic details of form submissions as follows:
```
$ netlify form submissions --form-id <form-id string>
```
That will return a list of the submission timestamp, name, and body.
=> Forms Functionality: Be able to view forms and submissions

configuration/configuration.go, configuration/configuration_test.go, configuration/test/netlify-headers-test.toml, glide.lock, glide.yaml
=> Replace TOML parser to support 4.0 syntax.

README.md
Scoop is very similar to Homebrew, but for Windows.
=> Add Scoop to the available installers for Windows.

site/_redirects
This adds a `site` folder with a single `_redirects` file. When published to Netlify, this generates redirects from consistent "latest" URLs to the direct download links for the latest release.
You can test the redirects in the branch deploy:
https://latest-release-redirects--cli.netlify.com/download/latest/mac
https://latest-release-redirects--cli.netlify.com/download/latest/linux
https://latest-release-redirects--cli.netlify.com/download/latest/windows
https://latest-release-redirects--cli.netlify.com/download/latest/source-zip
https://latest-release-redirects--cli.netlify.com/download/latest/source-tar
All of these redirects are 302 temporary, since they'll change with each new release. At the moment, the change will have to be manual, but we can add a script to automate it later.
I …
=> Add site with redirects for consistent latest-release URLs

commands/deploy/deploy.go
`p` was already taken and I didn't see it.
=> Fix shorthand definition.

site/_redirects
See the tag here: https://github.com/netlify/netlifyctl/releases/tag/v0.4.0
=> Update version links to 0.4.0.

README.md
Version 0.4.0 uploads netlify.toml files among the deployed files.
=> Remove info from the README that doesn't apply anymore.

commands/init/manual.go, commands/init/manual_test.go
I was running into an issue where `netlifyctl init --manual` was appending an extra ".git" extension to the repository URL.
Take this git remote for example:
```bash
[remote "origin"]
url = https://github.com/jakebellacera/example.git
```
This was causing the "Repository" property to be set as:
```
git@github.com:jakebellacera/example.git.git
```
... which is invalid.
This PR simply checks if the `repoUrl` ends with ".git", and if it doesn’t, then it will append it.
=> Don't append extra .git extension in repository URL if it already exists
