commands/deploy/deploy.go
commands/middleware/middleware.go
configuration/configuration.go
context/context.go
glide.lock
glide.yaml
main.go

I was thinking about this, I think that we should move the toml file parsing stuff into a separate lib.

deploy dir changes

---

commands/middleware/middleware.go

This is terrible but it fixes the issue uploading files.
We need to continue investigating the real problem, this is a temporary fix  since the client doesn't really take advantage of http/2 yet.

Disable H2 transport upgrade.

---

commands/deploy/deploy.go

Do not wait when there is nothing to upload.

---

commands/deploy/deploy.go

Goes with https://github.com/netlify/open-api/pull/14

Support draft deploys.

---

auth/auth.go
commands/commands.go
commands/login/login.go
glide.lock
glide.yaml

So people can login/signup from the CLI.
Fixes #3
Requires https://github.com/netlify/open-api/pull/19

Add `netlifyctl login` command.

---

commands/deploy/deploy.go
commands/netlify.go
operations/site.go

add list sites to deploy

---

commands/deploy/deploy.go
operations/site.go

```
No site configured in the netlify.toml, fetching your existing sites.
Choose a site to deploy to or 0 to create a new site.
[0] Create a new site
[1] ryan-support-testing
[2] statistician-audits-34073
=> Which site? (default: 0)
```
fixes #24

fix logic around creating or selecting a site

---

operations/site.go

Do not pass a nil validator to check the input before creating a deploy.

---

commands/deploy/deploy.go
glide.lock
glide.yaml

This allow people to set a specific message for a manual deploy.
Fixes #28.
/cc @fool

Add message flag for the deploy command.

---

.gitignore

Ignore tarballs

---

commands/commands.go
commands/deploy/deploy.go
commands/init/git.go
commands/init/github.go
commands/init/gitlab.go
commands/init/init.go
commands/init/manual.go
commands/netlify.go
commands/sites/update.go
glide.lock
glide.yaml
operations/site.go
ui/ui.go

- Support GitHub initialization
- Support Manual initialization
- Support GitLab initialization
Fixes #47 

Implement init command.

---

Makefile
commands/assets/assets.go
commands/deploy/deploy.go
commands/init/init.go
commands/init/manual.go
commands/middleware/middleware.go
commands/netlify.go
commands/sites/create.go
commands/sites/sites.go
configuration/configuration.go
glide.lock
glide.yaml
operations/deploy.go
operations/site.go
ui/task_tracker.go
ui/ui.go

This PR introduces changes in UI and messaging to the user.
- Use a spinner to track progress in tasks that take some time, like deploying and creating sites.
- Use colors to indice success and failure.
- Make the ctl term aware, enabling and disabling the UI if the ctl is used in terminal mode or not.

Improvements in messaging and UI

---

commands/middleware/middleware.go

Fix error message after dumping the debug log.

---

ui/ui.go

Always assume yes when the flag is enabled.

---

commands/deploy/deploy.go
ui/task_tracker.go
ui/ui.go

Fix progress tracker.

---

.gitignore
Makefile

- Builds binaries for all supported platforms.
- Uploads to GitHub using Hub.

Add make target to builds releases.

---

README.md

Make this version more up to date with the current features.

Update README to remove poc mention.

---

Makefile

Fix windows zip path.

---

glide.lock
glide.yaml

Fix issues with rate limited requests.

---

Makefile
commands/version.go

This gives more information about the version of the cli.

Display version and sha in version command.

---

commands/deploy/deploy.go

Use title from command line in deploy

---

README.md

In response to https://github.com/netlify/netlifyctl/issues/98 & https://github.com/netlify/netlifyctl/issues/93

Update instructions for installing from source

---

commands/init/git.go
commands/init/init.go
commands/init/manual.go
commands/init/manual_test.go
glide.lock
glide.yaml

So we fetch from the right remotes.
Fixes #86

Replace Git https urls with SSH in manual configurations.

---

commands/init/gitlab.go

- Abort if username or password are empty strings.
- Add password message.
- Fix session initialization.
Fixes #90

Fix GitLab user/password prompt.

---

commands/deploy/deploy.go
glide.lock
glide.yaml

expose preprocessing timeout

---

Makefile

Makefile Typo: s/PONY/PHONY

---

glide.lock
glide.yaml

Update open-api to fix issue with relative paths on Windows.

---

ui/ui.go

Assume defaults values when -y option is set.

---

appveyor.yml
glide.lock
glide.yaml

This will run tests on Appveyor on Windows.

Windows test environment.

---

site/_redirects

Update the redirect URLs to point to the latest release.

Update _redirects to 0.3.4 version

---

commands/init/github.go
commands/init/github_test.go
commands/init/gitlab.go
commands/init/gitlab_test.go
glide.lock
glide.yaml

Fixes #120
Fixes #110
Tested with GitHub https and ssh urls, and GitLab https and ssh urls.

Fix GitLab and GitHub init commands for different urls.

---

commands/deploy/deploy.go
configuration/configuration.go

Ensures that config changes are applied in post processing.
Fixes #95

Deploy config file from the root.

---

glide.lock
glide.yaml

See https://github.com/netlify/open-api/pull/90

Update open-api to allow zip based functions

---

README.md

fixing netlify.toml link
